name: experiment
save_experiment: False

# data options
data: 
  path: 'data\center_patches'
  image_size: 256

# model options
model:
  dilitation: [1, 2, 3, 4, 3, 2, 1]

# learning options
learning:
  loss: crossentropy          # name of loss. Can be crossentropy or PerplexiteLoss
  optimizer: adam             # optimizer. Only adam was implemented
  learning_rate: 0.01         # learning rate
  milesstone: [5, 15]         # gradient decay at epoch 5 and 15
  gamma: 0.1                  # learning rate will be multiplicate by 0.1 at epochs 5 and 15
  epochs: 30                  # number of epochs
  batch_size: 4               # batch size
  save_learning_curves: true  # save the learning curves at the end of experiements
  shuffle: true               # shuffle the data
  drop_last: true             # drop last batch (in order to have the same size at the end)
  device: cuda                # device: if device=cuda: cuda if available, other wise cpu

