name: little_model_test
save_experiment: true

# data options
data: 
  path: 'data\center_patches'
  image_size: 256
  noise_variance: 50
  random_variance: true

# model options
model:
  dilitation: [1, 2, 3, 2, 1]

# learning options
learning:
  loss: mse                   # name of loss. Only MSE is implemeted
  optimizer: adam             # optimizer. Only adam is implemented
  learning_rate: 0.01         # learning rate
  milesstone: [5, 15]         # gradient decay at epoch 5 and 15
  gamma: 0.1                  # learning rate will be multiplicate by 0.1 at epochs 5 and 15
  epochs: 2                   # number of epochs
  batch_size: 16              # batch size
  save_learning_curves: true  # save the learning curves at the end of experiements
  shuffle: true               # shuffle the data
  drop_last: true             # drop last batch (in order to have the same size at the end)
  device: cuda                # device: if device=cuda: cuda if available, other wise cpu
  save_checkpoint: true       # save model weigth during learning (best only according to the validation loss)

# metrics
metrics:
  PSNR: true
  MSSSIM: true